### ISSUE TITLE
Undefined index: RefreshTokenExpires

### ISSUE THREAD

**Issue by muresanandrei** [pallant/laravel-aws-cognito-auth#11]
I just got this error while trying to access every url

Undefined index: RefreshTokenExpires
in AwsCognitoIdentityGuard.php (line 300)

**Comment by ArranJacques** [comment]
It looks like some values are missing from the Cognito tokens that get stored in the session.

Try clearing all of your sessions and then re-authenticating the user. Hopefully that will fix it temporarily by causing the tokens to be re-generated and saved to the session.

I'll take a proper look on Monday at what could of caused those values to get dropped and will put a fix in place so that in fails more graceful in the event that this happens.

Thanks.

**Comment by ArranJacques** [comment]
See https://github.com/pallant/laravel-aws-cognito-auth/commit/6632925458ca24406486953ac901e129ab55f44f
