### ISSUE TITLE
Not working with Lumen 

### ISSUE THREAD

**Issue by hkbrain** [pallant/laravel-aws-cognito-auth#12]
Error when using Auth::attempt

Type error: Argument 1 passed to Pallant\LaravelAwsCognitoAuth\ServiceProvider::Pallant\LaravelAwsCognitoAuth\{closure}() must be an instance of Illuminate\Foundation\Application, instance of Laravel\Lumen\Application given, called in /home/himanshukoshti/html/mentisApi/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php on line 109

**Comment by ArranJacques** [comment]
Hi

At this time this package doesn't support Lumen.

With Lumen being stateless it requires some additional thought as to exactly how this work.

Since AWS Cognito requires a username and password to authenticate you'd have to send them with every request, unless you can authenticate with Cognito once and get the access token, map that to the user by storing it in the database or something, and then sending that access token with every request.

We will be supporting Lumen in the future but when we implement it we want to do it well so for the time being we're holding off until we get some spare time to focus on it.

Thanks

**Comment by phiter** [comment]
No updates then I guess, right?
